<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>cf49265d-5da4-47ed-95ce-57af2e329424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b95587b2-a048-4d2f-9ea3-cc826a9083c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>23581cd1-d37e-4494-a037-a2292d3de1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://frontend-entry-form-manual-uat.apps.ocp4dev.muf.co.id/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNzAwODAzMSIsImV4cCI6MTY4NjMwNjA1OSwiaWF0IjoxNjg2MjE5NjU5fQ.GU310hLl5Qiplw5GZof20PfymAdGu_nFswch6Jhe2ol5GNna7Lu6ErpW4C25y6AtVfn14Mk6P21XsPSaZs7hIg/692f3f757433fe60c772a2133a9f7bf7dcfb1eb93256cfcbe2448f5470197e29</value>
      <webElementGuid>4753ff7a-5b86-42f0-9e11-f701f227eaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex&quot;]/main[@class=&quot;content-main&quot;]/div[@class=&quot;padding-24&quot;]/view[@class=&quot;ng-star-inserted&quot;]/bgs-iframe[1]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/iframe[1]</value>
      <webElementGuid>9ced9d6d-7613-4839-a4f2-d180009ec866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>10b72a24-3249-4063-9b66-d9d268259f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'http://frontend-entry-form-manual-uat.apps.ocp4dev.muf.co.id/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNzAwODAzMSIsImV4cCI6MTY4NjMwNjA1OSwiaWF0IjoxNjg2MjE5NjU5fQ.GU310hLl5Qiplw5GZof20PfymAdGu_nFswch6Jhe2ol5GNna7Lu6ErpW4C25y6AtVfn14Mk6P21XsPSaZs7hIg/692f3f757433fe60c772a2133a9f7bf7dcfb1eb93256cfcbe2448f5470197e29']</value>
      <webElementGuid>e98d4b71-7e15-4431-8123-76755f392b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
