<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inp-nama-debefm</name>
   <tag></tag>
   <elementGuidId>d0c14a54-d3ae-4a92-a37e-cfb6820b0f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inp-nama-debefm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inp-nama-debefm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6fff3f3-ddc7-4ce6-ac2c-6695f12005d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>233359b3-7d36-48a9-a84b-9994b3dda479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>2fa3c496-e054-4d80-8580-4ccc5a70f40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NAMA SESUAI KTP</value>
      <webElementGuid>6cdfd01d-9596-4520-9af5-6926a1a62fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-nama-debefm</value>
      <webElementGuid>924934e4-a388-4d79-b517-bd2cc49088f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-nama-debefm&quot;)</value>
      <webElementGuid>58ac043c-5e6d-4176-a027-5dbdd4737164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>451d65b2-8826-41e0-a4aa-2512bc06d10e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inp-nama-debefm']</value>
      <webElementGuid>a633c3d1-c1fd-40b4-9441-53227e73df64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div/div/div[2]/div/input</value>
      <webElementGuid>c913c370-fe5d-4b8c-9aab-25c292de9136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>414e2af5-784b-492e-abbd-ca1d3218266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'NAMA SESUAI KTP' and @id = 'inp-nama-debefm']</value>
      <webElementGuid>5d488d36-0b2c-4d9e-bae9-e2779f2230ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
