<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inp-tempat-lahir-debefm</name>
   <tag></tag>
   <elementGuidId>3bad5a93-1c1a-4a28-b85c-cdf3a7ed4bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inp-tempat-lahir-debefm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inp-tempat-lahir-debefm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90b6ab1c-7428-48d0-a77e-145a2760ff5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>645512de-951e-428b-b575-d209ae3ed7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>de0da8e5-89b1-4636-b10f-1c76478bab56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TEMPAT LAHIR</value>
      <webElementGuid>2d866992-b177-40d3-9dab-744cdeea832c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-tempat-lahir-debefm</value>
      <webElementGuid>c3beb58f-907d-4a07-96b7-765fab4e7fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-tempat-lahir-debefm&quot;)</value>
      <webElementGuid>b3112033-6834-414e-9a9f-38e9736b6d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>e6129cc9-eedc-4114-a10a-9861565b15b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inp-tempat-lahir-debefm']</value>
      <webElementGuid>d052c75c-ef90-4f15-916c-482d58a1e641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div/div/div[3]/div/input</value>
      <webElementGuid>bfae1ead-f908-4542-8051-57f77d6be33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ce71b2cb-118d-44af-8ba3-1cc3af140fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'TEMPAT LAHIR' and @id = 'inp-tempat-lahir-debefm']</value>
      <webElementGuid>efec7d2c-f5a5-442c-8c58-8b482e09f44a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
