<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inp-tgl-lhr-debefm</name>
   <tag></tag>
   <elementGuidId>5722a1d6-d004-482e-9f72-0db0e62dc447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inp-tgl-lhr-debefm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inp-tgl-lhr-debefm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40b92f7f-10ea-43ca-a46a-2e574fde1d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-tgl-lhr-debefm</value>
      <webElementGuid>1b63fad1-795d-4974-8ed8-622424d51769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99338758-f442-4000-b4b5-47f1b66c620f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field datetimepicker-input tanggal inp-personal inp-tanggal </value>
      <webElementGuid>09f1c27a-a979-426d-a3c6-4899878e6a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>datetimepicker</value>
      <webElementGuid>8407216d-6960-4d9d-95e0-54d16ca9bf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-tgl-lhr-debefm&quot;)</value>
      <webElementGuid>8d1d44cc-9b86-42bf-8513-cf0d9cb282a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>99530876-5389-4773-91af-0bd58ec2e530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inp-tgl-lhr-debefm']</value>
      <webElementGuid>7bfb9169-a38c-459b-a2da-5b52b76c0a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div/div/div[4]/div/input</value>
      <webElementGuid>550348fb-55e0-43a8-ab53-c568759a9bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>85de2939-96e0-4462-8228-2c20535b2c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inp-tgl-lhr-debefm' and @type = 'input']</value>
      <webElementGuid>d285bec5-ca58-4a9c-aa6d-1061a9fdbcb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
