<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CUSTOMER PERSONAL - IDENTITAS_inp-ktp-debefm</name>
   <tag></tag>
   <elementGuidId>195fa7cd-fb67-40e3-b61c-10221e87328c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inp-ktp-debefm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inp-ktp-debefm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2dbf57-365d-4d88-9af2-df55922dcb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cfa1c87-8ee9-4673-806e-54310944e571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>36c0ec68-146a-4a5f-bde0-82f41e368839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NO KTP DEBITUR</value>
      <webElementGuid>a9cb4e07-768c-416c-98d9-bfd465134af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-ktp-debefm</value>
      <webElementGuid>cb4acc74-cfe2-4260-8f92-d37b5f81c50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>f3f5d710-bb49-4402-b2c3-41dc6d51aa4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-ktp-debefm&quot;)</value>
      <webElementGuid>44c06811-3b40-4b95-bf67-ede685defacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>a01de792-1724-46af-8b06-1fe2d5630218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inp-ktp-debefm']</value>
      <webElementGuid>e6643fe2-9bec-4235-aaa5-27c5a230d924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div/div/div/div/input</value>
      <webElementGuid>28a33e31-017b-411b-aae7-ae6496a0b94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>b14defc5-3e0c-4c53-9f06-c5be23ab0974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'NO KTP DEBITUR' and @id = 'inp-ktp-debefm']</value>
      <webElementGuid>0599dd18-d571-43f3-bbfd-44cd8e588a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
