<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_INFORMASI ALAMAT_inp-alamat-debefm</name>
   <tag></tag>
   <elementGuidId>1687eac5-db74-407b-acf0-557bab31672a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inp-alamat-debefm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inp-alamat-debefm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ee096351-576c-494b-b45d-689c0aba8e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__field</value>
      <webElementGuid>4ccebab5-2724-41b3-94c1-761dc16c7483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ALAMAT</value>
      <webElementGuid>8ad040d8-1850-47bc-b818-ae8375f5e3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp-alamat-debefm</value>
      <webElementGuid>0dc9f5fa-bd76-42f2-bf27-049fd6a7b977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>19fea298-04ec-46d3-b968-3bbb3fcd6702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp-alamat-debefm&quot;)</value>
      <webElementGuid>8437146c-b8ee-4278-b528-9aa4397ff851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>a8bbbcda-97da-4b8d-b6e6-61c0e90cb1dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inp-alamat-debefm']</value>
      <webElementGuid>b0be12e2-22ec-42f7-a5d8-0b22e7420c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div[2]/div[2]/div/div/textarea</value>
      <webElementGuid>7f2c2e1f-2ee1-4117-9b61-2145ef823980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d9d97e10-f6b5-43b4-9f08-3d3ccab723f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'ALAMAT' and @id = 'inp-alamat-debefm']</value>
      <webElementGuid>b981a2f6-2556-4ccd-873d-5dfb87960d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
