<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Dec_prev</name>
   <tag></tag>
   <elementGuidId>fb1ddbaf-5bf0-4fc2-a4b5-2cf4f9b3d708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showPersonal']/div/div/div[4]/div/div/ul/li/div/div[3]/table/thead/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.datepicker-years > table.table-condensed > thead > tr > th.prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>c1d0c383-0bc2-4081-a073-0a6f207284f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prev</value>
      <webElementGuid>95847f0d-7aa7-4539-998a-b4088e278607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>previous</value>
      <webElementGuid>10550975-4b40-407b-9376-7a1c27c070e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showPersonal&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form__group field&quot;]/div[@class=&quot;bootstrap-datetimepicker-widget dropdown-menu usetwentyfour bottom&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;show&quot;]/div[@class=&quot;datepicker&quot;]/div[@class=&quot;datepicker-years&quot;]/table[@class=&quot;table-condensed&quot;]/thead[1]/tr[1]/th[@class=&quot;prev&quot;]</value>
      <webElementGuid>34c6fd2e-225a-4bb7-83ef-c475b7ebbef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW ENTRY  Mandiri Utama Finance/iframe</value>
      <webElementGuid>33f4c888-e79e-4887-8d00-8b906e7ecc1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showPersonal']/div/div/div[4]/div/div/ul/li/div/div[3]/table/thead/tr/th</value>
      <webElementGuid>153e18aa-e30a-419b-8333-f4742d922a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/following::th[1]</value>
      <webElementGuid>f16fa9f1-8ea3-4bdf-8b62-52a45c24cc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov'])[1]/following::th[1]</value>
      <webElementGuid>ea77f964-1746-41a9-a4fe-30609164fde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::th[6]</value>
      <webElementGuid>8c9d3c75-b9bb-4bae-a8fe-7f7ff9c4cca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/thead/tr/th</value>
      <webElementGuid>de8e5ecb-148a-48f6-a940-050fb6d5a2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
